import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
 
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <meta name="viewport" content="width=1920px" />
      </Head>
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
